uploads = []
generated = []

[[outputs]]
id = "4-L1oyXkdU0XdL-m5tyMQ"
uri = "file://assets/images/splash-icon.png"
type = "image"
title = "MoodRx Splash — Space Grotesk"

[[outputs]]
id = "sAw6Qp2G2nN1xaWJIxqWA"
uri = "file://assets/images/splash-variant-a.png"
type = "image"
title = "A — MoodRx"

[[outputs]]
id = "eiMQakZLGzUqHAqhl1e6H"
uri = "file://assets/images/splash-variant-b.png"
type = "image"
title = "B — Mood ℞"
