import { MoodKey } from './storage';

export interface Supplement {
  name: string;
  benefit: string;
  evidenceLevel: string;
  evidenceSummary: string;
  cautions: string[];
  timing: string;
  dose: string;
  moods: MoodKey[];
  science: string;
  sources: string[];
}

export const SUPPLEMENTS: Supplement[] = [
  {
    name: 'Magnesium Glycinate',
    benefit: "Mixed anxiety evidence",
    evidenceLevel: "MIXED HUMAN EVIDENCE",
    evidenceSummary: "Evidence is mixed: 4 of 8 anxiety-vulnerable samples improved, while 4 showed no effect.",
    cautions: ["PREGNANCY / MEDICATION CHECK"],
    timing: 'Night',
    dose: 'Dosage varies',
    moods: ['anxious', 'stressed'],
    science: "Magnesium has been studied for anxiety, but the evidence is weak and mixed. In a 2017 systematic review, 4 of 8 studies in anxiety-vulnerable samples reported positive effects and 4 showed no effect; the review also found no validated subjective stress outcome. NHANES-based reviews report that many Americans consume less magnesium than the estimated average requirement. One small trial in older adults found magnesium improved insomnia scores, and a small ileal-resection study found magnesium diglycinate better tolerated or absorbed in some patients with impaired magnesium oxide absorption.",
    sources: [
      "Boyle et al. (2017). The effects of magnesium supplementation on subjective anxiety and stress. Nutrients.",
      "Rosanoff et al. (2012). Suboptimal magnesium status in the United States: are the health consequences underestimated? Nutr Rev.",
      "Abbasi et al. (2012). The effect of magnesium supplementation on primary insomnia. J Res Med Sci.",
      "Schuette et al. (1994). Bioavailability of magnesium diglycinate vs magnesium oxide in patients with ileal resection. JPEN J Parenter Enteral Nutr.",
    ],
  },
  {
    name: 'Omega-3 EPA/DHA',
    benefit: "EPA-focused mood evidence",
    evidenceLevel: "MODERATE HUMAN EVIDENCE",
    evidenceSummary: "EPA-dominant omega-3 formulas have more consistent depression-trial evidence than DHA-dominant formulas.",
    cautions: ["MEDICATION CHECK"],
    timing: 'With food',
    dose: 'Dosage varies',
    moods: ['low'],
    science: "Meta-analyses of depression trials report that omega-3 formulas with higher EPA content are more consistently associated with reduced depressive symptoms than DHA-dominant formulas, especially as adjunctive support. These studies support an EPA-focused depression claim; they do not prove a direct serotonin mechanism in humans.",
    sources: [
      "Sublette et al. (2011). Meta-analytic review of EPA antidepressant effects. J Clin Psychiatry.",
      "Firth et al. (2019). The efficacy and safety of nutrient supplements in the treatment of mental disorders. World Psychiatry.",
      "Grosso et al. (2014). Role of omega-3 fatty acids in depression. PLoS One.",
    ],
  },
  {
    name: '5-HTP',
    benefit: "Serotonin precursor evidence",
    evidenceLevel: "LIMITED HUMAN EVIDENCE",
    evidenceSummary: "Older small trials suggest possible antidepressant effects, but Cochrane found the evidence insufficient.",
    cautions: ["SEROTONIN MEDICATION CAUTION"],
    timing: 'Evening',
    dose: 'Dosage varies',
    moods: ['low'],
    science: "5-HTP is a serotonin precursor. Reviews of 5-HTP for depression found possible antidepressant effects in older small trials, but the Cochrane review concluded that the evidence was insufficient because available placebo-controlled data were limited and low quality. Do not combine 5-HTP with SSRIs, MAOIs, or other serotonergic drugs unless supervised by a clinician.",
    sources: [
      "Birdsall (1998). 5-Hydroxytryptophan: a clinically effective serotonin precursor. Altern Med Rev.",
      "Shaw et al. (2002). Tryptophan and 5-HTP for depression. Cochrane Database Syst Rev.",
    ],
  },
  {
    name: 'Ashwagandha KSM-66',
    benefit: "Studied cortisol reduction",
    evidenceLevel: "LIMITED HUMAN EVIDENCE",
    evidenceSummary: "One KSM-66 trial reported reduced stress scores and cortisol; broader ashwagandha evidence is limited and product-specific.",
    cautions: ["PREGNANCY / MEDICATION CHECK"],
    timing: 'Morning',
    dose: 'Dosage varies',
    moods: ['stressed', 'anxious'],
    science: "A 60-day randomized trial of KSM-66 ashwagandha root extract in chronically stressed adults reported larger reductions in perceived stress scores and serum cortisol than placebo. Broader reviews describe ashwagandha anxiety evidence as promising but limited by small and heterogeneous studies; results should not be assumed to apply to every ashwagandha product.",
    sources: [
      "Chandrasekhar et al. (2012). A prospective, randomized double-blind, placebo-controlled study of ashwagandha root extract in reducing stress and anxiety. Indian J Psychol Med.",
      "Pratte et al. (2014). An alternative treatment for anxiety: a systematic review of human trial results reported for the Ayurvedic herb ashwagandha. J Altern Complement Med.",
    ],
  },
  {
    name: 'L-Theanine',
    benefit: "Relaxed-alertness evidence",
    evidenceLevel: "LIMITED HUMAN EVIDENCE",
    evidenceSummary: "Small human studies support relaxed-alertness and acute stress-response claims.",
    cautions: [],
    timing: 'As needed',
    dose: 'Dosage varies',
    moods: ['anxious', 'restless'],
    science: "Small human studies report that L-theanine can increase alpha-band EEG activity associated with relaxed alertness and can reduce some acute stress-response measures. Human evidence supports limited acute stress/calmness claims; neurotransmitter changes such as GABA, serotonin, and dopamine increases are not established by these human citations.",
    sources: [
      "Nobre et al. (2008). L-theanine, a natural constituent in tea, and its effect on mental state. Asia Pac J Clin Nutr.",
      "Kimura et al. (2007). L-theanine reduces psychological and physiological stress responses. Biol Psychol.",
    ],
  },
  {
    name: 'GABA',
    benefit: "Sleep-onset evidence limited",
    evidenceLevel: "LIMITED HUMAN EVIDENCE",
    evidenceSummary: "This is about exogenous oral GABA; small studies suggest relaxation markers and sleep-onset effects, but brain GABA effects remain unresolved.",
    cautions: ["SLEEPINESS CAUTION"],
    timing: 'Evening',
    dose: 'Dosage varies',
    moods: ['restless'],
    science: "GABA made by the body is the brain's main inhibitory neurotransmitter, but this entry is about exogenous oral GABA supplements. Whether oral GABA meaningfully increases brain GABA in humans remains unresolved. Small human studies of oral GABA report relaxation-related marker changes and, in one fermented-rice-germ GABA trial, shorter sleep latency and improved sleep efficiency in people with insomnia symptoms.",
    sources: [
      "Abdou et al. (2006). Relaxation and immunity enhancement effects of GABA administration. Biofactors.",
      "Byun et al. (2018). Safety and efficacy of gamma-aminobutyric acid from fermented rice germ in patients with insomnia symptoms. J Clin Neurol.",
    ],
  },
  {
    name: 'Magnesium L-Threonate',
    benefit: "Brain-magnesium research",
    evidenceLevel: "PRECLINICAL + LIMITED HUMAN DATA",
    evidenceSummary: "Rodent brain-magnesium findings exist, plus limited older-adult cognitive data; human brain-magnesium superiority is not established.",
    cautions: ["PREGNANCY / MEDICATION CHECK"],
    timing: 'Night',
    dose: 'Dosage varies',
    moods: ['restless'],
    science: "Magnesium L-threonate increased brain magnesium and improved learning and memory measures in rodents. A small human study of a magnesium L-threonate-containing formula reported cognitive benefits in older adults with cognitive impairment. These citations do not establish human brain-magnesium superiority over other forms or a direct restlessness/sleep benefit.",
    sources: [
      "Slutsky et al. (2010). Enhancement of learning and memory by elevating brain magnesium. Neuron.",
      "Liu et al. (2016). Efficacy and safety of MMFS-01 (Mg-L-threonate) in older adults with cognitive impairment. J Alzheimers Dis.",
    ],
  },
  {
    name: 'Vitamin D3+K2',
    benefit: "Deficiency-linked mood support",
    evidenceLevel: "MIXED HUMAN EVIDENCE",
    evidenceSummary: "Low vitamin D is associated with depression, but supplementation results are mixed and most relevant when deficiency is present.",
    cautions: ["LAB-GUIDED"],
    timing: 'Morning',
    dose: 'Dosage varies',
    moods: ['low'],
    science: "Low vitamin D status is associated with depression in systematic reviews, but supplementation trials show mixed results and appear most relevant when deficiency is present. Vitamin K activates proteins involved in bone mineralization and inhibition of vascular calcification, but these citations do not prove D3+K2 prevents vascular disease in general supplement users.",
    sources: [
      "Anglin et al. (2013). Vitamin D deficiency and depression in adults: systematic review. Br J Psychiatry.",
      "Shaffer et al. (2014). Vitamin D supplementation for depressive symptoms. Psychosom Med.",
      "Holick (2007). Vitamin D deficiency. N Engl J Med.",
      "Wasilewski et al. (2019). The bone-vasculature axis: calcium supplementation and the role of vitamin K. Front Cardiovasc Med.",
    ],
  },
  {
    name: "Lion's Mane",
    benefit: "Preliminary cognitive evidence",
    evidenceLevel: "PRELIMINARY HUMAN EVIDENCE",
    evidenceSummary: "One small MCI trial and one small mood study exist; neurotrophic claims are mainly preclinical.",
    cautions: [],
    timing: 'Morning',
    dose: 'Dosage varies',
    moods: ['foggy'],
    science: "A small double-blind trial in older adults with mild cognitive impairment reported cognitive-score improvement after 16 weeks of Hericium erinaceus intake. A small study in women reported reductions in some depression and anxiety measures. Neurotrophic effects from compounds in Lion's Mane are supported mainly by preclinical and cell research, not by direct human evidence of neurogenesis or myelin repair.",
    sources: [
      "Mori et al. (2009). Improving effects of Hericium erinaceus on mild cognitive impairment: a double-blind placebo-controlled trial. Phytother Res.",
      "Nagano et al. (2010). Reduction of depression and anxiety by intake of Hericium erinaceus. Biomed Res.",
      "Lai et al. (2013). Neurotrophic properties of the Lion's Mane medicinal mushroom. Int J Med Mushrooms.",
    ],
  },
  {
    name: 'Phosphatidylserine',
    benefit: "Limited memory/stress evidence",
    evidenceLevel: "LIMITED HUMAN EVIDENCE",
    evidenceSummary: "Small studies suggest possible memory or stress-response effects, but findings vary by population and formulation.",
    cautions: [],
    timing: 'With breakfast',
    dose: 'Dosage varies',
    moods: ['foggy', 'stressed'],
    science: "Phosphatidylserine is a membrane phospholipid involved in neuronal signaling. Reviews and small human studies report possible benefits for some memory or stress-response measures, but findings vary by population, dose, and formulation. The FDA has allowed only qualified cognitive-function claims for phosphatidylserine, with language stating that the evidence is limited and preliminary.",
    sources: [
      "Glade & Smith (2015). Phosphatidylserine and the human brain. Nutrition.",
      "Kidd (1996). Phosphatidylserine; membrane nutrient for memory. Altern Med Rev.",
      "Benton et al. (2001). The influence of phosphatidylserine supplementation on mood and heart rate. Nutr Neurosci.",
    ],
  },
  {
    name: 'Rhodiola',
    benefit: "Stress-fatigue evidence",
    evidenceLevel: "LIMITED HUMAN EVIDENCE",
    evidenceSummary: "Small extract-specific trials suggest stress-fatigue or mental-performance effects under fatigue.",
    cautions: ["STIMULANT-LIKE CAUTION"],
    timing: 'Morning',
    dose: 'Dosage varies',
    moods: ['stressed', 'foggy'],
    science: "Small human trials of standardized Rhodiola rosea extracts report improvements in stress-related fatigue, mental performance during night duty, or attention under fatigue. The evidence is limited by small studies and extract-specific designs. The listed studies do not test stacking Rhodiola with ashwagandha.",
    sources: [
      "Olsson et al. (2009). A randomised, double-blind, placebo-controlled study of Rhodiola rosea in stress-related fatigue. Planta Med.",
      "Darbinyan et al. (2000). Rhodiola rosea in stress-induced fatigue. Phytomedicine.",
      "Panossian et al. (2010). Adaptogens: tonic herbs for fatigue and stress. Altern Ther Health Med.",
    ],
  },
  {
    name: 'B-Complex',
    benefit: "Stress and nutrient support",
    evidenceLevel: "MODERATE HUMAN EVIDENCE",
    evidenceSummary: "B-complex meta-analysis supports stress benefit, but not clear anxiety or depression benefit.",
    cautions: [],
    timing: 'Morning',
    dose: 'Dosage varies',
    moods: ['foggy', 'stressed'],
    science: "B vitamins participate in energy metabolism, methylation, and neurotransmitter-related pathways. A systematic review and meta-analysis of B-complex supplementation found a statistically significant benefit for stress, but not for anxiety and not clearly for depressive symptoms. Folate and B12 evidence is most relevant when low status or deficiency is present.",
    sources: [
      "Kennedy (2016). B Vitamins and the Brain: Mechanisms, Dose and Efficacy. Nutrients.",
      "Young et al. (2019). B vitamin supplementation on depressive symptoms, anxiety, and stress: systematic review and meta-analysis. Nutrients.",
      "Coppen & Bolander-Gouaille (2005). Treatment of depression: time to consider folic acid and B12. J Psychopharmacol.",
    ],
  },
  {
    name: 'Creatine Monohydrate',
    benefit: "Brain-energy evidence mixed",
    evidenceLevel: "MIXED HUMAN EVIDENCE",
    evidenceSummary: "Cognitive benefits appear possible in some groups or stressors, but not across all domains.",
    cautions: [],
    timing: 'Morning',
    dose: 'Dosage varies',
    moods: ['good'],
    science: "Creatine supports the phosphocreatine energy-buffering system. Human studies and reviews report possible benefits for memory or reasoning in some groups, including vegetarians, older adults, or people under cognitive stressors, but effects are not consistent across all cognitive domains. The listed citations do not prove that creatine preserves mood on a good day.",
    sources: [
      "Rae et al. (2003). Oral creatine monohydrate supplementation improves brain performance. Proc Biol Sci.",
      "McMorris et al. (2007). Creatine supplementation and cognitive performance. Neuropsychol Dev Cogn B Aging Neuropsychol Cogn.",
      "Avgerinos et al. (2018). Effects of creatine supplementation on cognitive function of healthy individuals. Exp Gerontol.",
    ],
  },
  {
    name: 'NAC',
    benefit: "Glutathione and glutamate research",
    evidenceLevel: "MIXED CLINICAL EVIDENCE",
    evidenceSummary: "NAC is researched in psychiatric conditions, but evidence is condition-specific and not healthy-person mood maintenance.",
    cautions: ["MEDICATION CHECK"],
    timing: 'With food',
    dose: 'Dosage varies',
    moods: ['good'],
    science: "N-acetylcysteine provides cysteine for glutathione synthesis and has been studied for oxidative-stress and glutamate-related pathways in psychiatric conditions. Clinical evidence is condition-specific and mixed. The listed studies support NAC as a researched adjunct in psychiatric disorders; they do not establish it as a healthy-person mood-maintenance or detox supplement.",
    sources: [
      "Berk et al. (2008). N-acetyl cysteine as a glutathione precursor for schizophrenia. Biol Psychiatry.",
      "Deepmala et al. (2015). Clinical trials of N-Acetylcysteine in psychiatry. Neurosci Biobehav Rev.",
    ],
  },
  {
    name: 'Zinc',
    benefit: "Depression-adjunct evidence",
    evidenceLevel: "DEPRESSION-ADJUNCT EVIDENCE",
    evidenceSummary: "Lower zinc is associated with depression, and small trials suggest adjunctive antidepressant support.",
    cautions: ["COPPER BALANCE CAUTION"],
    timing: 'With food',
    dose: 'Dosage varies',
    moods: ['low'],
    science: "Zinc is an essential trace mineral involved in many enzymes and neural signaling pathways. Meta-analysis shows lower peripheral zinc concentrations in people with depression compared with controls, and small clinical trials suggest zinc may help as an adjunct to antidepressant therapy. The listed citations do not prove that zinc improves mood in zinc-replete healthy users. Chronic high-dose zinc can impair copper status, so long-term use should be cautious.",
    sources: [
      "Cope & Levenson (2010). Role of zinc in the development and treatment of mood disorders. Curr Opin Clin Nutr Metab Care.",
      "Swardfager et al. (2013). Zinc in depression: a meta-analysis. Biol Psychiatry.",
      "Ranjbar et al. (2014). Effects of zinc supplementation on efficacy of antidepressant therapy. Nutr Neurosci.",
    ],
  },
  {
    name: 'Tyrosine',
    benefit: "Stress-demand cognition",
    evidenceLevel: "LIMITED HUMAN EVIDENCE",
    evidenceSummary: "Tyrosine may help cognition under sleep loss, cold/noise stress, or high cognitive demand.",
    cautions: ["BLOOD PRESSURE / MEDICATION CHECK"],
    timing: 'Morning (empty stomach)',
    dose: 'Dosage varies',
    moods: ['foggy'],
    science: "L-tyrosine is a precursor for catecholamines including dopamine and norepinephrine. Reviews and small acute studies suggest tyrosine can help preserve working memory or cognitive performance during sleep loss, cold/noise stress, or high cognitive demand. Evidence does not show broad cognitive benefit when catecholamine demand is not elevated.",
    sources: [
      "Jongkees et al. (2015). Effect of tyrosine supplementation on clinical and healthy populations under stress or cognitive demands. J Psychiatr Res.",
      "Neri et al. (1995). The effects of tyrosine on cognitive performance during extended wakefulness. Aviat Space Environ Med.",
      "Deijen & Orlebeke (1994). Effect of tyrosine on cognitive function and blood pressure. Brain Res Bull.",
    ],
  },
  {
    name: 'Alpha-GPC',
    benefit: "Cognitive-impairment evidence",
    evidenceLevel: "COGNITIVE-IMPAIRMENT EVIDENCE",
    evidenceSummary: "Evidence is strongest in cognitive impairment populations, not healthy focus enhancement.",
    cautions: [],
    timing: 'Morning',
    dose: 'Dosage varies',
    moods: ['foggy'],
    science: "Alpha-GPC is a choline-containing compound used in cholinergic pathways. Human evidence is strongest in Alzheimer's disease, vascular dementia, and related cognitive impairment, usually at higher clinical doses than typical supplement use. Evidence for focus or cognitive enhancement in healthy adults is limited and not established by the listed citations.",
    sources: [
      "De Jesus Moreno Moreno (2003). Cognitive improvement in mild-to-moderate Alzheimer's dementia after treatment with choline alfoscerate. Clin Ther.",
      "Parnetti et al. (2001). Choline alphoscerate in cognitive decline and acute cerebrovascular disease. Mech Ageing Dev.",
    ],
  },
  {
    name: 'Bacopa Monnieri',
    benefit: "Memory evidence over weeks",
    evidenceLevel: "MODERATE HUMAN EVIDENCE",
    evidenceSummary: "Standardized extracts show memory effects after chronic use; attention and stress findings are mixed.",
    cautions: [],
    timing: 'With food',
    dose: 'Dosage varies',
    moods: ['foggy', 'stressed'],
    science: "Randomized trials of standardized Bacopa monnieri extracts report improvements in some memory measures after chronic use, often around 12 weeks. Findings for attention, processing speed, anxiety, and stress are mixed across studies. The listed human trials do not directly support dendrite-branching or cortisol-reduction claims.",
    sources: [
      "Roodenrys et al. (2002). Chronic effects of Brahmi on human memory. Neuropsychopharmacology.",
      "Calabrese et al. (2008). Effects of a standardized Bacopa monnieri extract on cognitive performance. J Altern Complement Med.",
      "Stough et al. (2001). The chronic effects of an extract of Bacopa monniera on cognitive function in healthy human subjects. Psychopharmacology.",
    ],
  },
  {
    name: "St. John's Wort",
    benefit: "Depression evidence",
    evidenceLevel: "STRONG HUMAN EVIDENCE",
    evidenceSummary: "Cochrane found tested extracts superior to placebo and similar to antidepressants in short-term depression trials.",
    cautions: ["MAJOR MEDICATION INTERACTION"],
    timing: 'With food',
    dose: 'Dosage varies',
    moods: ['low'],
    science: "A Cochrane review found tested St. John's wort extracts were superior to placebo and similarly effective to standard antidepressants in short-term trials of major depression, with fewer adverse-effect dropouts. The review also reported heterogeneity and country-of-origin effects. St. John's wort has clinically important drug-interaction risks, so it should not be combined with medications without clinician review.",
    sources: [
      "Linde et al. (2008). St John's wort for major depression. Cochrane Database Syst Rev.",
      "Kasper et al. (2006). Superior efficacy of St John's wort extract WS 5570 compared to placebo in patients with major depression. BMC Med.",
    ],
  },
  {
    name: 'Saffron',
    benefit: "Depression trial evidence",
    evidenceLevel: "MODERATE HUMAN EVIDENCE",
    evidenceSummary: "Small trials and reviews suggest 30 mg/day saffron extract can reduce depressive symptoms.",
    cautions: [],
    timing: 'With food',
    dose: 'Dosage varies',
    moods: ['low', 'stressed'],
    science: "Small randomized trials and reviews suggest saffron extract, commonly around 30 mg/day, can reduce depressive symptoms in adults with mild-to-moderate depression. Some comparator trials reported symptom improvements similar to imipramine or fluoxetine, but these studies are small and do not prove antidepressant equivalence. Evidence for anxiety is less developed.",
    sources: [
      "Hausenblas et al. (2013). Saffron and depression: a systematic review. J Integr Med.",
      "Akhondzadeh et al. (2004). Comparison of saffron to imipramine for mild-to-moderate depression. BMC Complement Altern Med.",
      "Lopresti & Drummond (2014). Saffron for major depressive disorder: a meta-analysis of randomized clinical trials. Hum Psychopharmacol.",
    ],
  },
  {
    name: 'Lemon Balm',
    benefit: "Preliminary calming evidence",
    evidenceLevel: "PRELIMINARY HUMAN EVIDENCE",
    evidenceSummary: "One small acute study and one open-label pilot support preliminary calming/sleep-disturbance evidence.",
    cautions: [],
    timing: 'Evening',
    dose: 'Dosage varies',
    moods: ['anxious', 'restless'],
    science: "A small acute crossover study reported reduced laboratory-induced stress after Melissa officinalis. A separate open-label pilot study reported improvements in anxiety and sleep disturbance, but it was not placebo-controlled. Claims about GABA-transaminase inhibition or sleep latency are not established by these human citations.",
    sources: [
      "Kennedy et al. (2004). Attenuation of laboratory-induced stress in humans after administration of Melissa officinalis. Psychosom Med.",
      "Cases et al. (2011). Pilot trial of Melissa officinalis for anxiety disorders and sleep disturbances. Mediterr J Nutr Metab.",
    ],
  },
  {
    name: 'CoQ10',
    benefit: "Mitochondrial energy research",
    evidenceLevel: "CONDITION-SPECIFIC EVIDENCE",
    evidenceSummary: "CoQ10 has condition-specific fatigue research; healthy mental clarity evidence is not established.",
    cautions: [],
    timing: 'With food',
    dose: 'Dosage varies',
    moods: ['good'],
    science: "Coenzyme Q10 is a mitochondrial electron-transport cofactor and antioxidant. Clinical studies have evaluated CoQ10 for fatigue in specific conditions such as multiple sclerosis, but evidence for general mental clarity or cognitive enhancement in healthy adults is not established by the listed citations. Exercise-performance findings are mixed.",
    sources: [
      "Littarru & Tiano (2007). Bioenergetic and antioxidant properties of coenzyme Q10: recent developments. Mol Biotechnol.",
      "Sanoobar et al. (2016). Coenzyme Q10 as a treatment for fatigue and depression in multiple sclerosis. Nutr Neurosci.",
      "Garrido-Maraver et al. (2014). Clinical applications of coenzyme Q10. Front Biosci (Landmark Ed).",
    ],
  },
  {
    name: 'L-Methylfolate',
    benefit: "Folate pathway support",
    evidenceLevel: "DEPRESSION-ADJUNCT EVIDENCE",
    evidenceSummary: "Evidence is strongest for prescription-strength 15 mg/day adjunctive use in SSRI-resistant depression.",
    cautions: ["CLINICAL DOSE DIFFERS"],
    timing: 'Morning',
    dose: 'Dosage varies',
    moods: ['low'],
    science: "L-methylfolate is the bioactive folate form used in one-carbon metabolism and pathways that support monoamine synthesis. Clinical depression evidence is strongest for prescription-strength 15 mg/day L-methylfolate as an adjunct to SSRIs in patients with inadequate antidepressant response. The listed trials do not show that 400-1000 mcg treats depression or anxiety.",
    sources: [
      "Papakostas et al. (2012). L-methylfolate as adjunctive therapy for SSRI-resistant major depression. Am J Psychiatry.",
      "Stahl (2008). L-methylfolate: a vitamin for your monoamines. J Clin Psychiatry.",
      "Firth et al. (2019). The efficacy and safety of nutrient supplements in the treatment of mental disorders. World Psychiatry.",
    ],
  },
  {
    name: 'SAMe',
    benefit: "Depression evidence",
    evidenceLevel: "DEPRESSION EVIDENCE",
    evidenceSummary: "Older trials and one adjunctive trial support depression evidence, but studied doses differ.",
    cautions: ["BIPOLAR / MEDICATION CAUTION"],
    timing: 'Morning (empty stomach)',
    dose: 'Dosage varies',
    moods: ['low'],
    science: "SAMe is an endogenous methyl donor involved in methylation and monoamine-related pathways. Reviews of older trials report antidepressant effects versus placebo and similar short-term outcomes to tricyclic antidepressants, though study quality varies. A randomized adjunctive trial used 1600 mg/day in antidepressant nonresponders; the listed evidence does not establish 400-800 mg/day as an effective antidepressant dose.",
    sources: [
      "Papakostas et al. (2010). S-adenosyl methionine augmentation of serotonin reuptake inhibitors for antidepressant nonresponders. Am J Psychiatry.",
      "Mischoulon & Fava (2002). Role of S-adenosyl-L-methionine in the treatment of depression. Am J Clin Nutr.",
    ],
  },
  {
    name: 'Kava Kava',
    benefit: "Short-term anxiety evidence",
    evidenceLevel: "MIXED HUMAN EVIDENCE",
    evidenceSummary: "Some trials suggest GAD symptom benefit over weeks, but evidence is mixed and safety matters.",
    cautions: ["LIVER / ALCOHOL CAUTION"],
    timing: "Short-term use",
    dose: 'Dosage varies',
    moods: ['anxious', 'restless'],
    science: "Older trials and a 2013 randomized trial suggest some standardized kava extracts can reduce generalized anxiety symptoms over several weeks. Evidence is mixed, and kava is not established as an immediate as-needed anxiolytic. Liver safety, dose, duration, alcohol use, product quality, and medication interactions are important.",
    sources: [
      "Pittler & Ernst (2003). Kava extract versus placebo for treating anxiety. Cochrane Database Syst Rev.",
      "Lakhan & Vieira (2010). Nutritional and herbal supplements for anxiety and anxiety-related disorders. Nutr J.",
      "Sarris et al. (2013). Kava in the treatment of generalized anxiety disorder: a double-blind, randomized, placebo-controlled study. J Clin Psychopharmacol.",
    ],
  },
  {
    name: 'Passionflower',
    benefit: "Limited anxiety evidence",
    evidenceLevel: "LIMITED HUMAN EVIDENCE",
    evidenceSummary: "One small active-comparator GAD trial exists; larger placebo-controlled trials are needed.",
    cautions: [],
    timing: 'Evening',
    dose: 'Dosage varies',
    moods: ['anxious', 'restless'],
    science: "Passionflower has traditional use for anxiety and sleep, and preclinical work suggests GABA-system involvement. Human evidence is limited: one small active-comparator trial in generalized anxiety disorder found similar end-of-study anxiety improvements to oxazepam, with less job-performance impairment, but larger placebo-controlled trials are needed.",
    sources: [
      "Akhondzadeh et al. (2001). Passionflower in the treatment of generalized anxiety. J Clin Pharm Ther.",
      "Miroddi et al. (2013). Passiflora incarnata L.: ethnopharmacology, clinical application, safety and evaluation of clinical trials. J Ethnopharmacol.",
      "Janda et al. (2020). Passiflora incarnata in neuropsychiatric disorders: a systematic review. Nutrients.",
    ],
  },
  {
    name: 'Chamomile Extract',
    benefit: "GAD symptom evidence",
    evidenceLevel: "MODERATE HUMAN EVIDENCE",
    evidenceSummary: "Human trials support modest GAD symptom benefit; relapse prevention was not statistically significant.",
    cautions: [],
    timing: 'Evening',
    dose: 'Dosage varies',
    moods: ['anxious', 'stressed'],
    science: "Human trials support modest benefit for generalized anxiety disorder symptoms. A long-term randomized trial found lower ongoing GAD symptom scores during continuation treatment, but relapse prevention was not statistically significant. The clinical mechanism is not settled, and apigenin/GABA-A receptor claims are based on preclinical evidence rather than these human outcomes.",
    sources: [
      "Amsterdam et al. (2009). A randomized, double-blind, placebo-controlled trial of oral Matricaria recutita for generalized anxiety disorder. J Clin Psychopharmacol.",
      "Hieu et al. (2019). Therapeutic efficacy and safety of chamomile for state anxiety, generalized anxiety disorder, insomnia, and sleep quality. Phytother Res.",
      "Mao et al. (2016). Long-term chamomile treatment for generalized anxiety disorder: a randomized clinical trial. Phytomedicine.",
    ],
  },
  {
    name: 'Inositol',
    benefit: "Small panic/OCD trials",
    evidenceLevel: "PRELIMINARY HUMAN EVIDENCE",
    evidenceSummary: "Older small high-dose trials reported panic/OCD symptom improvement; evidence remains preliminary.",
    cautions: ["HIGH-DOSE STUDY"],
    timing: 'Split doses with meals',
    dose: 'Dosage varies',
    moods: ['anxious'],
    science: "Older small crossover trials studied high-dose myo-inositol, typically 12-18 g/day, for panic disorder and OCD. Some trials reported symptom improvement. Evidence is preliminary and mixed.",
    sources: [
      "Palatnik et al. (2001). Double-blind, controlled, crossover trial of inositol versus fluvoxamine for panic disorder. J Clin Psychopharmacol.",
      "Benjamin et al. (1995). Double-blind, placebo-controlled, crossover trial of inositol treatment for panic disorder. Am J Psychiatry.",
      "Fux et al. (1996). Inositol treatment of obsessive-compulsive disorder. Am J Psychiatry.",
    ],
  },
  {
    name: 'Melatonin',
    benefit: "Sleep timing support",
    evidenceLevel: "MODERATE HUMAN EVIDENCE",
    evidenceSummary: "Meta-analyses show modest sleep-latency and total-sleep-time effects; timing and dose depend on the sleep problem.",
    cautions: ["TIMING MATTERS"],
    timing: 'Before bed',
    dose: 'Dosage varies',
    moods: ['restless'],
    science: "Melatonin is primarily a circadian timing signal. Meta-analyses report modest improvements in sleep latency and total sleep time for some sleep disorders. Dose-response and timing depend on the sleep problem being targeted; the listed citations do not support a universal claim that 0.5 mg works as well as 5 mg for most people.",
    sources: [
      "Brzezinski et al. (2005). Effects of exogenous melatonin on sleep: meta-analysis. Sleep Med Rev.",
      "Ferracioli-Oda et al. (2013). Meta-analysis: melatonin for the treatment of primary sleep disorders. PLoS ONE.",
    ],
  },
  {
    name: 'Probiotics',
    benefit: "Gut-brain evidence mixed",
    evidenceLevel: "MIXED HUMAN EVIDENCE",
    evidenceSummary: "Depressive-symptom effects are small and strain-specific; anxiety findings are less consistent.",
    cautions: ["STRAIN-SPECIFIC"],
    timing: 'Morning (empty stomach)',
    dose: 'Dosage varies',
    moods: ['anxious', 'low', 'stressed'],
    science: "The gut-brain axis is biologically plausible, but probiotic effects are strain-, population-, and outcome-specific. Meta-analyses report small benefits for depressive symptoms in some populations, while anxiety findings are less consistent. Gut serotonin is mostly peripheral and does not directly enter the brain, so mood claims should not be based on gut serotonin production alone.",
    sources: [
      "Dinan et al. (2013). Psychobiotics: a novel class of psychotropic. Biol Psychiatry.",
      "Wallace & Milev (2017). The effects of probiotics on depressive symptoms in humans: systematic review. Ann Gen Psychiatry.",
      "Firth et al. (2019). The efficacy and safety of nutrient supplements in the treatment of mental disorders. World Psychiatry.",
    ],
  },
  {
    name: 'Valerian Root',
    benefit: "Sleep evidence mixed",
    evidenceLevel: "MIXED HUMAN EVIDENCE",
    evidenceSummary: "Some trials suggest subjective sleep benefits, but study quality and preparation differences limit conclusions.",
    cautions: ["SLEEPINESS CAUTION"],
    timing: 'Before bed',
    dose: 'Dosage varies',
    moods: ['restless', 'anxious'],
    science: "Valerian contains constituents that may affect GABA-A-related pathways in preclinical studies. Human sleep evidence is mixed: some trials and reviews suggest possible subjective sleep-quality or sleep-latency benefits, but study quality, preparation differences, and guideline reviews make firm conclusions difficult. It should be framed as uncertain sleep support rather than a reliable insomnia treatment.",
    sources: [
      "Bent et al. (2006). Valerian for sleep: a systematic review and meta-analysis. Am J Med.",
      "Leathwood et al. (1982). Aqueous extract of valerian root improves sleep quality. Pharmacol Biochem Behav.",
      "Shinjyo et al. (2020). Valerian root in treating sleep problems and associated disorders: systematic review and meta-analysis. J Evid Based Integr Med.",
    ],
  },
];

export function getSupplementsForMood(mood: MoodKey): Supplement[] {
  return SUPPLEMENTS.filter((s) => s.moods.includes(mood));
}
