import { MoodKey } from './storage';

export interface Supplement {
  name: string;
  benefit: string;
  timing: string;
  dose: string;
  moods: MoodKey[];
  science: string;
  sources: string[];
  /** Safety / interaction note shown alongside the science. Optional. */
  safety?: string;
}

export const SUPPLEMENTS: Supplement[] = [
  {
    name: 'Magnesium Glycinate',
    benefit: 'Calms nervous system',
    timing: 'Night',
    dose: '200-400mg',
    moods: ['anxious', 'stressed'],
    science: "Magnesium helps run your GABA system — the brain's main “calm down” signal. And most people run low: NHANES data shows roughly 48% of Americans don't even hit the estimated average requirement, usually without realizing it. The glycinate form absorbs far better than cheap magnesium oxide, which mostly just sends you to the bathroom.",
    sources: [
      'Boyle et al. (2017). The effects of magnesium supplementation on subjective anxiety and stress: a systematic review. Nutrients, 9(5), 429.',
      'Rosanoff et al. (2012). Suboptimal magnesium status in the United States: are the health consequences underestimated? Nutrition Reviews, 70(3), 153–164.',
      'Abbasi et al. (2012). The effect of magnesium supplementation on primary insomnia in the elderly: a double-blind placebo-controlled clinical trial. Journal of Research in Medical Sciences.',
    ],
    safety: 'Magnesium can add to the effect of sedatives and may cause loose stools at higher doses. Check with your doctor if you take other medications or have kidney issues.',
  },
  {
    name: 'Omega-3 EPA/DHA',
    benefit: 'Serotonin support',
    timing: 'With food',
    dose: '1-2g',
    moods: ['low'],
    science: "EPA and DHA build your brain's cell membranes. Lower omega-3 levels are linked to weaker serotonin signaling. Across meta-analyses it's EPA — not DHA — that carries the antidepressant effect, likely by calming inflammation in neural tissue. Go for a supplement where EPA is the dominant fraction (aim for 60%+ EPA).",
    sources: [
      'Sublette et al. (2011). Meta-analysis of the effects of eicosapentaenoic acid (EPA) in clinical trials in depression. Journal of Clinical Psychiatry, 72(12), 1577–1584.',
      'Su et al. (2008). Omega-3 fatty acids for major depressive disorder during pregnancy: results from a randomized, double-blind, placebo-controlled trial. Journal of Clinical Psychiatry, 69(4), 644–651.',
      'Grosso et al. (2014). Role of omega-3 fatty acids in the treatment of depressive disorders: a comprehensive meta-analysis of randomized clinical trials. PLoS One, 9(5), e96905.',
    ],
    safety: 'High-dose fish oil (above ~3g/day) can thin the blood — talk to your doctor if you take anticoagulants or have surgery coming up.',
  },
  {
    name: '5-HTP',
    benefit: 'Serotonin precursor',
    timing: 'Evening',
    dose: '50-100mg',
    moods: ['low'],
    science: "5-HTP is the direct precursor to serotonin — one step before the final molecule. Unlike tryptophan, it crosses into the brain easily without competing with other amino acids for transport. Some small trials suggest it helps mood, but the highest-quality review (Cochrane) calls the evidence inconclusive — promising, not proven.",
    sources: [
      'Birdsall (1998). 5-Hydroxytryptophan: a clinically effective serotonin precursor. Alternative Medicine Review, 3(4), 271–280.',
      'Shaw et al. (2002). Tryptophan and 5-hydroxytryptophan for depression. Cochrane Database of Systematic Reviews, (1), CD003198.',
      'Nakajima et al. (1978). Clinical evaluation of 5-hydroxy-L-tryptophan as an antidepressant drug. Folia Psychiatrica et Neurologica Japonica, 32(2), 223–230.',
    ],
    safety: 'Serious interaction risk. Do NOT combine 5-HTP with SSRIs, SNRIs, MAOIs, triptans, tramadol, or other serotonergic drugs — the combination can cause serotonin syndrome, which can be life-threatening. Clear it with your doctor or pharmacist first.',
  },
  {
    name: 'Ashwagandha KSM-66',
    benefit: 'Cortisol reduction',
    timing: 'Morning',
    dose: '300-600mg',
    moods: ['stressed', 'anxious'],
    science: "KSM-66 is a specific full-spectrum extract. In a 60-day randomized trial, it cut serum cortisol by about 28% versus placebo. It's an adaptogen — it modulates your stress response rather than sedating you. KSM-66 is one of the most studied extracts; generic ashwagandha is more of a dice roll.",
    sources: [
      'Chandrasekhar et al. (2012). A prospective, randomized double-blind, placebo-controlled study of safety and efficacy of a high-concentration full-spectrum extract of ashwagandha root in reducing stress and anxiety in adults. Indian Journal of Psychological Medicine, 34(3), 255–262.',
      'Pratte et al. (2014). An alternative treatment for anxiety: a systematic review of human trial results reported for the Ayurvedic herb ashwagandha (Withania somnifera). Journal of Alternative and Complementary Medicine, 20(12), 901–908.',
      'Choudhary et al. (2017). Efficacy and safety of ashwagandha (Withania somnifera) root extract in improving memory and cognitive functions. Journal of Dietary Supplements, 14(6), 599–612.',
    ],
    safety: 'Not recommended in pregnancy. Can interact with thyroid, sedative, and immunosuppressant medications; rare reports of liver injury. Check with your doctor if you take other medications.',
  },
  {
    name: 'L-Theanine',
    benefit: 'Calm focus',
    timing: 'As needed',
    dose: '100-200mg',
    moods: ['anxious', 'restless'],
    science: "L-Theanine nudges your brain toward alpha-wave activity — the relaxed-but-alert state — without making you drowsy. Human studies show it lowers heart rate and stress responses under pressure. It's a big part of why green tea calms you despite the caffeine. Kicks in around 30-40 minutes.",
    sources: [
      'Nobre et al. (2008). L-theanine, a natural constituent in tea, and its effect on mental state. Asia Pacific Journal of Clinical Nutrition, 17(S1), 167–168.',
      'Kimura et al. (2007). L-theanine reduces psychological and physiological stress responses. Biological Psychology, 74(1), 39–45.',
      'Ritsner et al. (2011). L-theanine relieves positive, activation, and anxiety symptoms in patients with schizophrenia and schizoaffective disorder. Journal of Clinical Psychiatry, 72(1), 34–42.',
    ],
    safety: 'Generally well tolerated. May add to the effect of blood-pressure medication or other calming agents.',
  },
  {
    name: 'GABA',
    benefit: 'Nervous system brake',
    timing: 'Evening',
    dose: '250-500mg',
    moods: ['restless'],
    science: "GABA is your brain's primary inhibitory neurotransmitter — it slows neural activity down. When GABA signaling is low, your brain won't stop firing, which is what restlessness feels like. Oral GABA doesn't cross the blood-brain barrier well, so the evidence is mixed — but some small studies suggest it may lower stress markers and ease sleep onset. Take it 30-60 minutes before you wind down.",
    sources: [
      'Abdou et al. (2006). Relaxation and immunity enhancement effects of gamma-aminobutyric acid (GABA) administration in humans. BioFactors, 26(3), 201–208.',
      'Byun et al. (2018). Safety and efficacy of gamma-aminobutyric acid from fermented rice germ in patients with insomnia symptoms: a randomized, double-blind trial. Journal of Clinical Neurology, 14(3), 291–295.',
    ],
    safety: 'Can compound the drowsiness of alcohol, sleep aids, or sedatives — don’t combine without medical advice.',
  },
  {
    name: 'Magnesium L-Threonate',
    benefit: 'Brain calming',
    timing: 'Night',
    dose: '1-2g',
    moods: ['restless'],
    science: "Magnesium L-Threonate is the form best studied for reaching the brain and raising brain magnesium — work that started at MIT. It targets synaptic magnesium, which helps regulate the NMDA receptors behind excitatory “won't-quiet-down” signaling. Most of the direct brain-level evidence is still early (animal studies plus small human trials on cognition). It costs more than glycinate, and that's the trade.",
    sources: [
      'Slutsky et al. (2010). Enhancement of learning and memory by elevating brain magnesium. Neuron, 65(2), 165–177.',
      "Liu et al. (2016). Efficacy and safety of MMFS-01, a synapse density enhancer, for treating cognitive impairment in older adults. Journal of Alzheimer's Disease, 49(4), 971–990.",
    ],
    safety: 'Magnesium can add to the effect of sedatives and may cause loose stools at higher doses. Check with your doctor if you take other medications or have kidney issues.',
  },
  {
    name: 'Vitamin D3+K2',
    benefit: 'Mood baseline',
    timing: 'Morning',
    dose: '2-5K IU',
    moods: ['low', 'foggy'],
    science: "Vitamin D receptors sit throughout your brain, including regions tied to mood. Roughly 40% of Americans run low, and low vitamin D is consistently linked to depression — though supplement trials are mixed, with the clearest benefit in people who are actually deficient. The K2 is there for teamwork: D3 ramps up calcium absorption, and K2 helps steer that calcium toward your bones.",
    sources: [
      'Anglin et al. (2013). Vitamin D deficiency and depression in adults: systematic review and meta-analysis. British Journal of Psychiatry, 202(2), 100–107.',
      'Shaffer et al. (2014). Vitamin D supplementation for depressive symptoms: a systematic review and meta-analysis of randomized controlled trials. Psychosomatic Medicine, 76(3), 190–196.',
      'Holick (2007). Vitamin D deficiency. New England Journal of Medicine, 357(3), 266–281.',
    ],
    safety: 'Vitamin D is fat-soluble, so very high doses over time can build up. K2 can interact with blood thinners (warfarin) — check with your doctor if you take one.',
  },
  {
    name: "Lion's Mane",
    benefit: 'Cognitive support',
    timing: 'Morning',
    dose: '500-1000mg',
    moods: ['foggy'],
    science: "Lion's Mane contains hericenones and erinacines — compounds shown in lab studies to trigger Nerve Growth Factor (NGF). The human evidence is early: a small double-blind trial in older adults with mild cognitive impairment saw cognitive gains, and a tiny 4-week study reported lower anxiety and low mood. Promising, not proven — most of the mechanism work is still in cells and animals.",
    sources: [
      'Mori et al. (2009). Improving effects of the mushroom Yamabushitake (Hericium erinaceus) on mild cognitive impairment: a double-blind placebo-controlled clinical trial. Phytotherapy Research, 23(3), 367–372.',
      'Nagano et al. (2010). Reduction of depression and anxiety by 4 weeks Hericium erinaceus intake. Biomedical Research, 31(4), 231–237.',
      "Lai et al. (2013). Neurotrophic properties of the Lion's Mane medicinal mushroom, Hericium erinaceus, from Malaysia. International Journal of Medicinal Mushrooms, 15(6), 539–554.",
    ],
    safety: 'Generally well tolerated; rare allergic skin or respiratory reactions. May add to the effect of blood thinners.',
  },
  {
    name: 'Phosphatidylserine',
    benefit: 'Memory & clarity',
    timing: 'With breakfast',
    dose: '100-300mg',
    moods: ['foggy', 'stressed'],
    science: "Phosphatidylserine is a structural phospholipid in your brain-cell membranes. It supports membrane signaling and acetylcholine activity, and small trials show it can blunt cortisol spikes under acute stress. The FDA allows a “qualified” health claim for cognitive function in older adults — “qualified” meaning the evidence is still preliminary, but promising enough to be recognized.",
    sources: [
      'Glade & Smith (2015). Phosphatidylserine and the human brain. Nutrition, 31(6), 781–786.',
      'Kidd (1996). Phosphatidylserine; membrane nutrient for memory. Alternative Medicine Review, 1(2), 70–84.',
      'Benton et al. (2001). The influence of phosphatidylserine supplementation on mood and heart rate when faced with an acute stressor. Nutritional Neuroscience, 4(3), 169–178.',
    ],
    safety: 'Most supplements are soy- or sunflower-derived (note if you have a soy allergy). Generally safe; may cause mild stomach upset.',
  },
  {
    name: 'Rhodiola',
    benefit: 'Anti-fatigue',
    timing: 'Morning',
    dose: '200-400mg',
    moods: ['stressed', 'foggy'],
    science: "Rhodiola is an adaptogen that targets mental fatigue. In a placebo-controlled trial (Olsson et al., 2009), about four weeks of use produced meaningful drops in burnout and better attention. It works on the HPA stress axis, like ashwagandha but through a different route — so people often pair them.",
    sources: [
      'Olsson et al. (2009). A randomised, double-blind, placebo-controlled, parallel-group study of the standardised extract SHR-5 of the roots of Rhodiola rosea in subjects with stress-related fatigue. Planta Medica, 75(2), 105–112.',
      'Darbinyan et al. (2000). Rhodiola rosea in stress induced fatigue — a double blind cross-over study of a standardized extract SHR-5. Phytomedicine, 7(5), 365–371.',
      'Panossian & Wikman (2010). Effects of adaptogens on the central nervous system and the molecular mechanisms associated with their stress-protective activity. Pharmaceuticals, 3(1), 188–224.',
    ],
    safety: 'Can feel activating or cause jitteriness — take it earlier in the day. Use caution if you have bipolar disorder or take stimulants.',
  },
  {
    name: 'B-Complex',
    benefit: 'NT synthesis',
    timing: 'Morning',
    dose: '1 cap',
    moods: ['low', 'foggy', 'stressed'],
    science: "B vitamins are direct cofactors in neurotransmitter synthesis — your brain can't produce serotonin, dopamine, or norepinephrine without B6, B9, and B12. Stress burns through B vitamins faster than normal. A shortfall doesn't announce itself as “vitamin deficiency” — it can show up as low mood, brain fog, and fatigue. Which is why most people never connect the dots.",
    sources: [
      'Kennedy (2016). B vitamins and the brain: mechanisms, dose and efficacy — a review. Nutrients, 8(2), 68.',
      'Young (1993). The use of diet and dietary components in the study of factors controlling affect in humans: a review. Journal of Psychiatry & Neuroscience, 18(5), 235–244.',
      'Coppen & Bolander-Gouaille (2005). Treatment of depression: time to consider folic acid and vitamin B12. Journal of Psychopharmacology, 19(1), 59–65.',
    ],
    safety: 'Generally safe. Very high-dose B6 over long periods (well above typical B-complex amounts) can cause nerve symptoms — stick to standard doses.',
  },
  {
    name: 'Creatine Monohydrate',
    benefit: 'Brain energy & performance',
    timing: 'Morning',
    dose: '3-5g',
    moods: ['good'],
    science: "Creatine isn't just for gym bros. Your brain runs on phosphocreatine as a fast energy reserve — trials show creatine can sharpen working memory and processing speed, most clearly under sleep loss or mental load, and most in people who start low (vegetarians, the sleep-deprived). One of the cheapest, best-studied, safest supplements going — and plain monohydrate works as well as the fancy forms.",
    sources: [
      'Rae et al. (2003). Oral creatine monohydrate supplementation improves brain performance: a double-blind, placebo-controlled, cross-over trial. Proceedings of the Royal Society B, 270(1529), 2147–2150.',
      'McMorris et al. (2006). Effect of creatine supplementation and sleep deprivation, with mild exercise, on cognitive and psychomotor performance, mood state, and plasma concentrations of catecholamines and cortisol. Psychopharmacology, 185(1), 93–103.',
      'Avgerinos et al. (2018). Effects of creatine supplementation on cognitive function of healthy individuals: a systematic review of randomized controlled trials. Experimental Gerontology, 108, 166–173.',
    ],
    safety: 'Very safe for healthy people. Stay well hydrated.',
  },
  {
    name: 'NAC',
    benefit: 'Glutathione boost',
    timing: 'With food',
    dose: '600-1200mg',
    moods: ['good'],
    science: "N-Acetyl Cysteine is a building block your body uses to make glutathione, its main antioxidant. It also nudges glutamate signaling — the pathway researchers have studied for compulsive and obsessive patterns. Think of NAC as low-key upkeep for your antioxidant system. Most of the evidence is in clinical settings, so treat it as maintenance, not a mood fix.",
    sources: [
      'Berk et al. (2008). N-acetyl cysteine as a glutathione precursor for schizophrenia — a double-blind, randomized, placebo-controlled trial. Biological Psychiatry, 64(5), 361–368.',
      'Deepmala et al. (2015). Clinical trials of N-acetylcysteine in psychiatry and neurology: a systematic review. Neuroscience & Biobehavioral Reviews, 55, 294–321.',
    ],
    safety: 'Generally well tolerated; can cause stomach upset. May add to the effect of blood thinners at high doses.',
  },
  {
    name: 'Zinc',
    benefit: 'NT regulation',
    timing: 'With food',
    dose: '15-30mg',
    moods: ['good'],
    science: "Zinc is a cofactor for roughly 300 enzymes, and it's involved in the dopamine, serotonin, and GABA systems. Low zinc has been linked to low mood and poor stress resilience, and mild shortfalls are more common than people realize. When you're feeling good, enough zinc helps keep that balance steady. Take it with food — on an empty stomach it can cause nausea.",
    sources: [
      'Cope & Levenson (2010). Role of zinc in the development and treatment of mood disorders. Current Opinion in Clinical Nutrition & Metabolic Care, 13(6), 685–689.',
      'Nowak et al. (2003). Effect of zinc supplementation on antidepressant therapy in unipolar depression: a preliminary placebo-controlled study. Polish Journal of Pharmacology, 55(6), 1143–1147.',
    ],
    safety: "Don't stack multiple zinc sources long-term — chronic high intake (above ~40mg/day) can cause copper deficiency.",
  },
  {
    name: 'Tyrosine',
    benefit: 'Dopamine precursor',
    timing: 'Morning (empty stomach)',
    dose: '500-2000mg',
    moods: ['foggy', 'low'],
    science: "L-Tyrosine is the precursor to L-DOPA, which the brain turns into dopamine and norepinephrine. Under heavy cognitive load, sleep deprivation, or acute stress, your brain burns through these faster than diet replaces them. Tyrosine acts as a metabolic safety net — topping up the raw materials so demanding work holds up better. The effect shows up mainly when you're actually depleted, not on an ordinary day.",
    sources: [
      'Jongkees et al. (2015). Effect of tyrosine supplementation on clinical and healthy populations under stress or cognitive demands — a review. Journal of Psychiatric Research, 70, 50–57.',
      'Neri et al. (1995). The effects of tyrosine on cognitive performance during extended wakefulness. Aviation, Space, and Environmental Medicine, 66(4), 313–319.',
      'Deijen & Orlebeke (1994). Effect of tyrosine on cognitive function and blood pressure under stress. Brain Research Bulletin, 33(3), 319–323.',
    ],
    safety: 'Avoid with MAOI antidepressants. Use caution with hyperthyroidism, or if you take levodopa (they compete for absorption). Take on an empty stomach.',
  },
  {
    name: 'Alpha-GPC',
    benefit: 'Choline & focus',
    timing: 'Morning',
    dose: '300-600mg',
    moods: ['foggy', 'good'],
    science: "Alpha-GPC is a choline source that crosses into the brain and feeds acetylcholine — the neurotransmitter behind focus and working memory. Most of the strong cognitive trials are in older adults with dementia, so its everyday benefit for healthy people is less established. If your diet is low in choline (eggs, organ meats), it's a direct top-up.",
    sources: [
      "De Jesus Moreno Moreno (2003). Cognitive improvement in mild to moderate Alzheimer's dementia after treatment with the acetylcholine precursor choline alfoscerate. Clinical Therapeutics, 25(1), 178–193.",
      'Parnetti et al. (2007). Cholinergic precursors in the treatment of cognitive impairment of vascular origin: ineffective approaches or need for re-evaluation? Journal of the Neurological Sciences, 257(1-2), 264–269.',
      'Bellar et al. (2015). The effect of 6 days of alpha glycerylphosphorylcholine on isometric strength. Journal of the International Society of Sports Nutrition, 12, 42.',
    ],
    safety: 'Generally well tolerated short-term. Some observational data has linked high choline intake to cardiovascular risk signals — don’t overdo it.',
  },
  {
    name: 'Bacopa Monnieri',
    benefit: 'Memory & calm',
    timing: 'With food',
    dose: '300-600mg',
    moods: ['foggy', 'stressed'],
    science: "Bacopa is an Ayurvedic herb with one of the better human evidence bases for memory. In animal studies it boosts dendrite branching — more connections between neurons — and multiple human RCTs show gains in delayed recall, processing speed, and attention, plus lower anxiety. The catch: it takes 8-12 weeks to fully kick in. Not instant, but the evidence is real.",
    sources: [
      'Roodenrys et al. (2002). Chronic effects of Brahmi (Bacopa monnieri) on human memory. Neuropsychopharmacology, 27(2), 279–281.',
      'Calabrese et al. (2008). Effects of a standardized Bacopa monnieri extract on cognitive performance, anxiety, and depression in the elderly. Journal of Alternative and Complementary Medicine, 14(6), 707–713.',
      'Stough et al. (2001). The chronic effects of an extract of Bacopa monniera (Brahmi) on cognitive function in healthy human subjects. Psychopharmacology, 156(4), 481–484.',
    ],
    safety: 'Commonly causes stomach upset (cramping, nausea, loose stools) — take it with food.',
  },
  {
    name: "St. John's Wort",
    benefit: 'Mild-moderate depression',
    timing: 'With food',
    dose: '300mg (0.3% hypericin)',
    moods: ['low'],
    science: "St. John's Wort is one of the most studied herbal antidepressants in the world. A 2008 Cochrane review of 29 trials found it more effective than placebo and similarly effective to standard antidepressants for mild-to-moderate depression, with fewer side effects. It likely works through several pathways, including serotonin, dopamine, and norepinephrine.",
    sources: [
      "Linde et al. (2008). St John's wort for major depression. Cochrane Database of Systematic Reviews, (4), CD000448.",
      "Kasper et al. (2006). Superior efficacy of St John's wort extract WS 5570 compared to placebo in patients with major depression: a randomized, double-blind, placebo-controlled, multi-center trial. BMC Medicine, 4, 14.",
    ],
    safety: "Major interaction risk — bigger than most people realize. St. John's Wort speeds up the liver enzymes that clear many drugs, which can make them stop working: birth control (risk of unintended pregnancy), blood thinners, HIV and transplant medications, some chemo, and certain heart and seizure meds. It can also cause serotonin syndrome with antidepressants. Don't combine it with prescription meds without talking to your doctor or pharmacist.",
  },
  {
    name: 'Saffron',
    benefit: 'Mood elevation',
    timing: 'With food',
    dose: '30mg',
    moods: ['low', 'stressed'],
    science: "Saffron — yes, the spice — keeps showing up in depression research. A meta-analysis of several small RCTs found it beat placebo, and a few head-to-head pilot trials found it roughly on par with standard antidepressants — though those trials were small and mostly from one region, so treat it as promising, not settled. Its active compounds (crocin, safranal) appear to nudge serotonin, GABA, and glutamate. The effective dose is tiny — around 30mg/day of standardized extract.",
    sources: [
      'Hausenblas et al. (2013). Saffron (Crocus sativus L.) and major depressive disorder: a meta-analysis of randomized clinical trials. Journal of Integrative Medicine, 11(6), 377–383.',
      'Akhondzadeh et al. (2004). Comparison of Crocus sativus L. and imipramine in the treatment of mild to moderate depression: a pilot double-blind randomized trial. BMC Complementary and Alternative Medicine, 4, 12.',
      'Lopresti & Drummond (2014). Saffron (Crocus sativus) for depression: a systematic review of clinical studies and examination of underlying antidepressant mechanisms of action. Human Psychopharmacology, 29(6), 517–527.',
    ],
    safety: 'Stick to about 30mg/day — high doses (around 5g) are toxic. Avoid in pregnancy, as it can stimulate the uterus.',
  },
  {
    name: 'Lemon Balm',
    benefit: 'Calming & sleep',
    timing: 'Evening',
    dose: '300-600mg',
    moods: ['anxious', 'restless'],
    science: "Lemon balm (Melissa officinalis) appears to work on the GABA system — lab studies suggest it slows GABA breakdown and interacts with GABA receptors. Human studies point to less anxiety and better sleep, and it's mild enough to use situationally without the next-day fog of heavier sleep aids. Many people pair it with L-Theanine for an extra-calm combo.",
    sources: [
      'Kennedy et al. (2004). Attenuation of laboratory-induced stress in humans after acute administration of Melissa officinalis (lemon balm). Psychosomatic Medicine, 66(4), 607–613.',
      'Cases et al. (2011). Pilot trial of Melissa officinalis L. leaf extract in the treatment of volunteers suffering from mild-to-moderate anxiety disorders and sleep disturbances. Mediterranean Journal of Nutrition and Metabolism, 4(3), 211–218.',
    ],
    safety: 'May add to the effect of sedatives and thyroid medication; use caution if you take either.',
  },
  {
    name: 'CoQ10',
    benefit: 'Cellular energy',
    timing: 'With food',
    dose: '100-300mg',
    moods: ['good'],
    science: "Coenzyme Q10 sits in your mitochondria's electron transport chain, where cells make energy. Levels dip with age. Most of the clearer fatigue benefit comes from studies in people with specific conditions (like multiple sclerosis), so the everyday lift for healthy people is less certain. The ubiquinol form may absorb better than ubiquinone, especially as you get older.",
    sources: [
      'Littarru & Tiano (2007). Bioenergetic and antioxidant properties of coenzyme Q10: recent developments. Molecular Biotechnology, 37(1), 31–37.',
      'Sanoobar et al. (2016). Coenzyme Q10 as a treatment for fatigue and depression in multiple sclerosis patients: a double blind randomized clinical trial. Nutritional Neuroscience, 19(3), 138–143.',
      'Garrido-Maraver et al. (2014). Clinical applications of coenzyme Q10. Frontiers in Bioscience (Landmark Edition), 19(4), 619–633.',
    ],
    safety: 'Can reduce the effect of warfarin (a blood thinner) and may modestly lower blood pressure — check with your doctor if either applies.',
  },
  {
    name: 'L-Methylfolate',
    benefit: 'Neurotransmitter synthesis',
    timing: 'Morning',
    dose: '400-1000mcg',
    moods: ['low', 'anxious'],
    science: "L-methylfolate is the active, brain-ready form of vitamin B9 — the form your neurons actually use in the methylation cycle that helps build serotonin, dopamine, and norepinephrine. Regular folic acid has to be converted first, and if you carry a common MTHFR gene variant your body does that conversion poorly. In one set of trials, adding L-methylfolate (at the higher 15mg dose) helped people who hadn't fully responded to an SSRI.",
    sources: [
      'Papakostas et al. (2012). L-methylfolate as adjunctive therapy for SSRI-resistant major depression. American Journal of Psychiatry, 169(12), 1267–1274.',
      'Stahl (2008). L-methylfolate: a vitamin for your monoamines. Journal of Clinical Psychiatry, 69(9), 1352–1353.',
      'Firth et al. (2019). The efficacy and safety of nutrient supplements in the treatment of mental disorders: a meta-review of meta-analyses of randomized controlled trials. World Psychiatry, 18(3), 308–324.',
    ],
    safety: 'Generally well tolerated. High-dose folate can mask a B12 deficiency — worth a B12 check. Check with your doctor if you take methotrexate or anti-seizure meds.',
  },
  {
    name: 'SAMe',
    benefit: 'Mood & methylation',
    timing: 'Morning (empty stomach)',
    dose: '400-800mg',
    moods: ['low'],
    science: "SAMe is your body's main methyl donor — it fuels the reactions that build and recycle serotonin, dopamine, and norepinephrine. Randomized trials suggest it can lift mood, including as an add-on for people who didn't fully respond to an SSRI, and it's generally well tolerated. Some older, smaller trials also compared it with antidepressants, but the evidence base is still limited.",
    sources: [
      'Papakostas et al. (2010). S-adenosyl methionine (SAMe) augmentation of serotonin reuptake inhibitors for antidepressant nonresponders with major depressive disorder. American Journal of Psychiatry, 167(8), 942–948.',
      'Mischoulon & Fava (2002). Role of S-adenosyl-L-methionine in the treatment of depression: a review of the evidence. American Journal of Clinical Nutrition, 76(5), 1158S–1161S.',
      'Firth et al. (2019). The efficacy and safety of nutrient supplements in the treatment of mental disorders: a meta-review of meta-analyses of randomized controlled trials. World Psychiatry, 18(3), 308–324.',
    ],
    safety: 'Talk to your doctor before combining SAMe with antidepressants — together they can push serotonin too high (serotonin syndrome). It can also trigger mania or agitation in people with bipolar disorder.',
  },
  {
    name: 'Kava Kava',
    benefit: 'Acute anxiety relief',
    timing: 'As needed',
    dose: '150-300mg kavalactones',
    moods: ['anxious', 'restless'],
    science: "Kava's active compounds — kavalactones — modulate GABA-A receptors, and several RCTs show a modest reduction in anxiety on standardized scales (the Cochrane review calls the effect small). It's one of the few botanicals with real anxiolytic trial data.",
    sources: [
      'Pittler & Ernst (2003). Kava extract versus placebo for treating anxiety. Cochrane Database of Systematic Reviews, (1), CD003383.',
      'Lakhan & Vieira (2010). Nutritional and herbal supplements for anxiety and anxiety-related disorders: systematic review. Nutrition Journal, 9, 42.',
    ],
    safety: '⚠️ Liver warning: kava has been linked to rare but serious liver injury, including liver failure, and is restricted or banned in several countries. Don’t use it if you have liver problems, drink heavily, or take medications processed by the liver. Stop and see a doctor if you notice yellowing skin or eyes, dark urine, or persistent fatigue. Talk to a clinician before trying kava.',
  },
  {
    name: 'Passionflower',
    benefit: 'Baseline anxiety',
    timing: 'Evening',
    dose: '300-500mg',
    moods: ['anxious', 'restless'],
    science: "Passionflower works on the GABA system — lab studies suggest it boosts GABA activity through more than one pathway. In practice, people use it for the physical side of anxiety: the jitters, the butterflies, the tension. A small clinical trial found it eased generalized anxiety with fewer daytime side effects than a common prescription option. Better for simmering baseline anxiety than acute panic.",
    sources: [
      'Akhondzadeh et al. (2001). Passionflower in the treatment of generalized anxiety: a pilot double-blind randomized controlled trial with oxazepam. Journal of Clinical Pharmacy and Therapeutics, 26(5), 363–367.',
      'Miroddi et al. (2013). Passiflora incarnata L.: ethnopharmacology, clinical application, safety and evaluation of clinical trials. Journal of Ethnopharmacology, 150(3), 791–804.',
    ],
    safety: 'Can increase drowsiness with sedatives, sleep aids, or alcohol; not recommended in pregnancy. Talk to your doctor if you take anxiety or sleep medication.',
  },
  {
    name: 'Chamomile Extract',
    benefit: 'Generalized anxiety',
    timing: 'Evening',
    dose: '220-1100mg',
    moods: ['anxious', 'stressed'],
    science: "Chamomile's apigenin appears to act on GABA-A receptors at the benzodiazepine site, though with weak affinity. Its strength is the long game: an 8-week RCT showed modest anxiety reduction, and a 26-week continuation trial found fewer generalized-anxiety relapses versus placebo. Better for chronic background worry than acute panic.",
    sources: [
      'Amsterdam et al. (2009). A randomized, double-blind, placebo-controlled trial of oral Matricaria recutita (chamomile) extract therapy for generalized anxiety disorder. Journal of Clinical Psychopharmacology, 29(4), 378–382.',
      'Mao et al. (2016). Long-term chamomile (Matricaria chamomilla L.) treatment for generalized anxiety disorder: a randomized clinical trial. Phytomedicine, 23(14), 1735–1742.',
      'Hieu et al. (2019). Therapeutic efficacy and safety of chamomile for state anxiety, generalized anxiety disorder, insomnia, and sleep quality: a systematic review and meta-analysis. Phytotherapy Research, 33(6), 1604–1615.',
    ],
    safety: 'Can add to the effect of sedatives and blood thinners. Avoid if you’re allergic to ragweed or related plants.',
  },
  {
    name: 'Inositol',
    benefit: 'Panic & OCD threshold',
    timing: 'Split doses with meals',
    dose: '12-18g (powder)',
    moods: ['anxious', 'restless'],
    science: "Inositol only does much at high doses — the trials used 12-18g a day. Two small crossover RCTs found it reduced panic attacks versus placebo, and in one trial it performed comparably to the SSRI fluvoxamine with fewer side effects. Small studies, so promising rather than settled. Panic disorder is a medical condition — talk to a clinician before self-treating, especially at these doses.",
    sources: [
      'Palatnik et al. (2001). Double-blind, controlled, crossover trial of inositol versus fluvoxamine for the treatment of panic disorder. Journal of Clinical Psychopharmacology, 21(3), 335–339.',
      'Benjamin et al. (1995). Double-blind, placebo-controlled, crossover trial of inositol treatment for panic disorder. American Journal of Psychiatry, 152(7), 1084–1086.',
    ],
    safety: 'High doses can cause mild nausea, gas, or loose stools. Panic disorder needs proper care — don’t use this as a substitute for treatment.',
  },
  {
    name: 'Melatonin',
    benefit: 'Circadian sleep reset',
    timing: 'Before bed',
    dose: '0.5-5mg',
    moods: ['restless'],
    science: "Melatonin is a neurohormone, not a sedative. It doesn't knock you out — it signals the suprachiasmatic nucleus (your brain's master clock) that it's nighttime, lowering core body temperature and easing the sympathetic nervous system down. The common mistake is taking too much: for many people a low dose (around 0.5mg) works about as well as a higher one. Most effective for circadian misalignment (shift work, jet lag, delayed sleep phase) — pair it with good sleep habits.",
    sources: [
      'Brzezinski et al. (2005). Effects of exogenous melatonin on sleep: a meta-analysis. Sleep Medicine Reviews, 9(1), 41–50.',
      'Ferracioli-Oda et al. (2013). Meta-analysis: melatonin for the treatment of primary sleep disorders. PLoS ONE, 8(5), e63773.',
    ],
    safety: 'Can cause next-day drowsiness and may interact with blood thinners, blood-pressure, and diabetes medications. Don’t drive until you know how it affects you.',
  },
  {
    name: 'Probiotics',
    benefit: 'Gut-brain mood axis',
    timing: 'Morning (empty stomach)',
    dose: '10-50 billion CFU',
    moods: ['anxious', 'low', 'stressed'],
    science: "Most of your body's serotonin (around 90%) is made in the gut — and while that gut serotonin doesn't directly cross into your brain, the gut and brain stay in constant conversation along the vagus nerve. Specific “psychobiotic” strains of Lactobacillus and Bifidobacterium have shown early promise for mood and anxiety in human trials, though results are mixed and strongest in people who are actually struggling. The strains matter: look for ones with human clinical data (like L. helveticus R0052 + B. longum R0175) rather than generic blends.",
    sources: [
      'Dinan et al. (2013). Psychobiotics: a novel class of psychotropic. Biological Psychiatry, 74(10), 720–726.',
      'Wallace & Milev (2017). The effects of probiotics on depressive symptoms in humans: a systematic review. Annals of General Psychiatry, 16, 14.',
      'Firth et al. (2019). The efficacy and safety of nutrient supplements in the treatment of mental disorders: a meta-review of meta-analyses of randomized controlled trials. World Psychiatry, 18(3), 308–324.',
    ],
    safety: 'Generally safe for healthy adults. Use caution if you are severely immunocompromised or critically ill (rare infection risk).',
  },
  {
    name: 'Valerian Root',
    benefit: 'Sleep onset',
    timing: 'Before bed',
    dose: '300-600mg',
    moods: ['restless', 'anxious'],
    science: "Valerian is thought to boost GABA activity, the brain's main “slow down” signal. The evidence is mixed — a meta-analysis of 16 trials found inconsistent results and uneven study quality, though valerian is notable for causing little next-day grogginess. Worth a try for mild sleeplessness; not a sure thing.",
    sources: [
      'Bent et al. (2006). Valerian for sleep: a systematic review and meta-analysis. American Journal of Medicine, 119(12), 1005–1012.',
      'Leathwood et al. (1982). Aqueous extract of valerian root (Valeriana officinalis L.) improves sleep quality in man. Pharmacology Biochemistry and Behavior, 17(1), 65–71.',
    ],
    safety: 'Can add to the effects of alcohol, benzodiazepines, and other sedatives — don’t combine, and don’t drive after taking until you know how it affects you.',
  },
];

export function getSupplementsForMood(mood: MoodKey): Supplement[] {
  return SUPPLEMENTS.filter((s) => s.moods.includes(mood));
}
